const whatItDo = {
    mobile: 'Recruiter will contact on this number.',
    bio: 'It is the first thing recruiters notice in your profile. Write concisely what makes you unique and right person for the job you are looking for.',
    overview: 'Your Profile Overview should mention the highlights of your career and education, what your professional interests are, and what kind of a career you are looking for. Write a meaningful overview of more than 50 characters.',
    employment: 'Mention your employment details including your current and previous company work experience.',
    education: 'Please mention your education details. You can add details about your school, college and degree. This will increase your profile strength.',
    onlineProfile: 'It helps recruiters know more about you, and increase the chances to get a interview call.',
    project: 'Add details about projects you have done in college, internship or at work.',
    skills: 'Tell recruiters what you know or what you are known for e.g. Direct Marketing, Oracle, Java etc. We will send you job recommendations based on these skills.',
    location: 'Tell recruiters where you are based. Helps recruiter to analyze right fit for them.',
    industry: 'Helps us to improve suggestions and filter search results for you.',
    designation: 'Helps us to improve suggestions and filter search results for you.',
    company: 'Helps seekers to know which company is they are applied for.',
    roleAtCompany: '....',
    companySize: 'These are the meta data for the company display on the job applications and recruiter profile.',
    salary: 'Salary information helps us find relevant jobs for you', 
    experience: 'This helps recruiters know your years of experience', 
    currentSalary: 'Salary information helps us find relevant jobs for you', 
    noticePeriod: 'Lets recruiters know your availability to join', 
    gender: 'This information is important for employers to know you better', 
    religion: 'This information is important for employers to know you better', 
    maritalStatus: 'This information is important for employers to know you better', 
    birthDate: 'This information is important for employers to know you better', 
    prefJobType: 'This information helps us deliver well suite jobs to you',
    prefEmploymentType: 'This information helps us deliver well suite jobs to you',
    prefLocation: 'This information helps us deliver well suite jobs to you',
    expectedCtc: 'This information helps us deliver well suite jobs to you',
};

export default whatItDo;